export const ADD_CARD_TO_DECK = 'ADD_CARD_TO_DECK';
export const REMOVE_CARD_FROM_DECK = 'REMOVE_CARD_FROM_DECK';
export const SET_ACTIVE_DECK_NUMBER = 'SET_ACTIVE_DECK_NUMBER';
export const CLEAR_ACTIVE_DECK = 'CLEAR_ACTIVE_DECK';
